declare module '@editorjs/paragraph'
declare module '@editorjs/header'
declare module '@editorjs/link'
declare module '@editorjs/quote'
declare module '@editorjs/delimiter'
declare module '@editorjs/marker'
declare module '@editorjs/table'
declare module '@editorjs/list'
// declare module '@editorjs/nested-list'
// declare module '@editorjs/embed'